# SECursor ~/.secursor/config.yaml global config file.
#
# This file is used to configure the SECursor environment for all sessions.
# It is merged with a project's .secursor/config.yaml file if it exists.

# Set a specific version of Cursor to use, or "latest" to use the latest
# version.
cursor:
  version: latest

# This string value is split into words and then combined and deduplicated with
# any values in the project's .secursor/config.yaml file.
# The values are installed using apt-get during the container build.
apt-get:
  jq
  silversearcher-ag
  tig
  tmate
  tree
